### ISSUE TITLE
Data changes aren't animating

### ISSUE THREAD

**Issue by MaxAst** [margelo/react-native-graph#115]
Thanks for this great library! Everything's been working well, apart from the animation on data changes demonstrated in the gifs of the README. I provided a repro using Expo Go [here](https://github.com/MaxAst/react-native-graph-repro), using the code from your example. Likely caused by different skia versions, I'm using the latest one in my example

https://github.com/user-attachments/assets/4d7af8ee-4efe-4161-bf31-6e5679a175c0

**Comment by billyjacoby** [comment]
Seeing the same issue on my end as well. I've tried with both the latest version - `1.5.0` as well as `1.2.3` and `0.1.233`

**Comment by MaxAst** [comment]
I changed to [`victory`](https://github.com/FormidableLabs/victory/) and in their docs it says that skia animations only work if the data points length is the same across ranges. Might be the same for this library
