### ISSUE TITLE
BarChart component?

### ISSUE THREAD

**Issue by Mvrs** [margelo/react-native-graph#13]
First off I would like to thank the team for delivering this amazing library.

I was wondering do you have plans to implement a <BarChart /> component. Many health conscious apps utilize this for displaying performance metrics or weekly comparisons for their calories, hours of sleep; etc.

Just thought it would be cool 🥹🙃

Thanks

**Comment by mrousavy** [comment]
Hey! Thanks! No, we don't have that planned. (yet?)
