### ISSUE TITLE
The graph is not drawing outliers 

### ISSUE THREAD

**Issue by eduardborges** [margelo/react-native-graph#20]
<img width="535" alt="Screen Shot 2022-06-11 at 11 48 29 AM" src="https://user-images.githubusercontent.com/5917885/173182863-259cc07a-732d-4967-b10d-5bb352aea4da.png">

Both charts have the same exact data; the one above (react-native-graph) is not drawing the outliers. I checked `onPointSelected`, and the data is correct. The problem is with the line.

**Comment by mrousavy** [comment]
Valid - that's because we do some rounding/averaging in this library. This should probably be considered though, I mean we could force draw a point for every pixel even if it's multiple...

**Comment by chrispader** [comment]
Maybe the latest changes from versions `0.2.0` and above could be helpful to you. You can define a `smoothing` prop there, that sets how much smoothing should be applied.

**Comment by vm-agnislav** [comment]
Yeah, they were removed in #62 :( . And that was exactly what we needed. Any other option to draw outliers?
