### ISSUE TITLE
Graph opacity is faded when animated = True

### ISSUE THREAD

**Issue by nopshusang** [margelo/react-native-graph#23]
Pretty basic setup. Pan gesture isn't enabled
```
<Box height={350}>
  <LineGraph
      style={styles.chart}
      points={dataPoints}
      color={colors[accentColorTheme]}
      lineThickness={2}
      animated={true}
    />
</Box>
```
When `animated={true}`
![Screen Shot 2022-06-14 at 11 02 51 PM](https://user-images.githubusercontent.com/1551175/173754134-52475997-536f-4d20-a1f5-fb1ea75961d3.png)

When `animated={false}`
![image](https://user-images.githubusercontent.com/1551175/173754157-bbfa2764-053b-4e76-91bc-ee1806ced262.png)

**Comment by amansharma20** [comment]
Setting enablePanGesture={true} solved it for me

**Comment by amansharma20** [comment]
Facing the same issue. Did you find any solution to that?

**Comment by mrousavy** [comment]
Ah yes, that's a bug! Maybe https://github.com/margelo/react-native-graph/pull/14 fixes this?

**Comment by nopshusang** [comment]
@mrousavy Thanks for looking into this. Setting the `initialIndex` in that PR would fix it yeah. However, I'm not sure if `initialIndex` needs to be a prop. Highlighting 100% of the chart should just be a default behavior for the initial render and when there is no ongoing gesture.

The PR could be a temporary solution though. Are you planning to approve it?

**Comment by nopshusang** [comment]
@mrousavy actually [this](https://github.com/margelo/react-native-graph/commit/df0b8b21c43db8167fdc4fe5877b2953c8504c8e) fixes it. Could you just release an update? Thanks!

**Comment by nopshusang** [comment]
The [solution above](https://github.com/margelo/react-native-graph/pull/14) technically fixes it. However, it breaks the initial fingerX position after the hold. The right fix for it is to move the check into the `setFingerX` callback
```
pathEnd.current = isActive.value ? fingerX / width : 1
```
I recommend you revert that solution and put this one in instead
