### ISSUE TITLE
selection point not moving 

### ISSUE THREAD

**Issue by vardan0107** [margelo/react-native-graph#26]
Code:
`import {View, Text, SafeAreaView, StyleSheet} from 'react-native';
import React from 'react';
import {useNavigation} from '@react-navigation/native';
import {getMutualFund} from '../services/MutualFundApi';
import {LineGraph} from 'react-native-graph';
import {hapticFeedback} from './hapticFeedBack';
export default function MutualFundDetailScreen({route}) {
  const navigation = useNavigation();
  const loadMFDetails = async scheme_name => {
    let data = await getMutualFund(scheme_name);
    console.log(data);
    let tempArray = [];
    data.data.map(item => {
      var newdate = item.date.split('-').reverse().join('-');
      tempArray.push({
        data: new Date(newdate).getTime(),
        value: Number(item.nav),
      });
    });
    setPointsArray(tempArray);
    setMfData(data);
  };
  React.useEffect(() => {
    if (route.params != undefined) {
      console.log(route.params.code);
      loadMFDetails(route.params.code);
    }
  }, []);
  const [mfData, setMfData] = React.useState(null);
  const [value, setValue] = React.useState(0);
  const [date, setDate] = React.useState(0);
  const [pointsArray, setPointsArray] = React.useState([]);

  return (
    <SafeAreaView style={styles.container}>
      <Text>{value}</Text>
      <Text>{new Date(date).toString('MMM dd')}</Text>
      <View>
        <LineGraph
          color="#31CBD1"
          style={{height: 200, width: 300, marginLeft:30}}
          points={pointsArray.reverse()}
          animated={true}
          enablePanGesture={true}
          selectionDotShadowColor="#333333"
          onGestureStart={() => hapticFeedback('impactLight')}
          onPointSelected={p => {
            setValue(p.value);
            setDate(p.data);
        }}
        />
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
});
`
<img width="349" alt="Screenshot 2022-06-24 at 2 54 06 AM" src="https://user-images.githubusercontent.com/88476015/175405171-88e90251-7355-4564-99e2-898f8bf2821c.png">

pointer is present at top corner , not moving when i drag my finger on graph,

**Comment by sunnylqm** [comment]
reverted react-native-skia to 0.1.123 then it back to normal

**Comment by acorscadden** [comment]
Ugh, I was having the same issue and couldn't figure it out. I also set `react-native-skia` to `0.1.123` and that fixed it for me too.

**Comment by chrispader** [comment]
This should be fixed with `react-native-graph@0.2.0` and the latest skia version.

**Comment by sunrise1002** [comment]
I currently have this issue with 
```
"react-native-gesture-handler": "^2.12.1"
"react-native-reanimated": "^3.5.0"
"@shopify/react-native-skia": "^0.1.202"
"react-native-graph": "^1.0.2"
```

**Comment by puelocesar** [comment]
I'm currently having the same issue with:

```
"react-native-gesture-handler": "~2.20.2",
"react-native-reanimated": "~3.16.1",
"@shopify/react-native-skia": "^1.12.4",
"react-native-graph": "^1.1.0",
```

Do I need to upgrade to latest RN for this to work?
