### ISSUE TITLE
Dot position on Line graph not follow when pan gesture

### ISSUE THREAD

**Issue by nwpnkmngm** [margelo/react-native-graph#27]
I've followed by example project but got dot on line graph not follow on the line

here is video 

https://user-images.githubusercontent.com/48342930/177480944-33620bc2-f813-4912-bd30-2941fe181a80.MP4

**Comment by talal-tilted** [comment]
Hello ! same for me, followed the example project.. can someone help us plz ?

**Comment by talal-tilted** [comment]
@[nwpnkmngm] (https://github.com/nwpnkmngm)https://github.com/margelo/react-native-graph/issues/26#issuecomment-1168198282 seems to fix the issue
