### ISSUE TITLE
Get X axis value

### ISSUE THREAD

**Issue by skeie** [margelo/react-native-graph#3]
Thanks for this great library 👏. I have one question about `TopAxisLabel / BottomAxisLabel`

In the doc it states: 

`You can get the maximum and minimum values from your graph points array, and smoothly animate the labels on the X axis accordingly.`

I'm wondering how we can translate the max and min values from the GraphPoints to the correct x-axis points? I.E if the max value of the graph is 1337, how can we find the corresponding X value for it?

**Comment by mrousavy** [comment]
Well you can find this by iterating through the data array, then doing `x = index / points.length * graphWidth`

I'll maybe add a label component to the lib to make this easier!

**Comment by skeie** [comment]
Ah, perfect - thank you so much!

**Comment by Angelk90** [comment]
@skeie : Can you show the code of how you created your label?
