### ISSUE TITLE
Can't import AxisLabel 

### ISSUE THREAD

**Issue by davydspotnana** [margelo/react-native-graph#4]
Thanks for this module, animation works very well!

Can you also add an `AxisLabel` component, that you mention in a README file?

**Comment by skeie** [comment]
This might help you, so you can create your own: https://github.com/margelo/react-native-graph/issues/3

**Comment by Angelk90** [comment]
@skeie : Can you show the code of how you created your label?

**Comment by skeie** [comment]
Something like this @Angelk90 :

```
function AxisLabel() {
    const x =
        (INDEX_OF_YOUR_MAX_OR_MIN_VALUE / LENGTH_OF_YOUR_POINTS_ARRAY) *
        GRAPH_WIDTH;

    return (
        <View style={{ transform: [{ translateX: Math.max(x - 22, 5) }] }}>
            <Text color='darkPurple'>
                {YOUR_MAX_OR_MIN_VALUE}
            </Text>
        </View>
    );
}
```

**Comment by chrispader** [comment]
Will close this, as the example from @skeie should be enough to make it work :)
