### ISSUE TITLE
useDerivedValue is deprecated in Skia

### ISSUE THREAD

**Issue by omida86** [margelo/react-native-graph#40]
https://github.com/Shopify/react-native-skia/pull/753/commits/2f45037e7f0a71df21ba113ee567cff642986fc0

`useDerivedValue` should be changed to `useComputedValue`.

**Comment by 3210jr** [comment]
Looks like this was already fixed in this commit here: https://github.com/margelo/react-native-graph/commit/dffaa4bcaf583983d22d2e80f52b5c4e11318a68 . Probably not published to npm yet

**Comment by omida86** [comment]
Is it going to be published or is this library dead?
