### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'maxValue.getTime')

### ISSUE THREAD

**Issue by bomxacalaka** [margelo/react-native-graph#46]
Can't use the simplest example without getting this error

> TypeError: undefined is not an object (evaluating 'maxValue.getTime')

```
import { LineGraph } from 'react-native-graph'

priceHistory = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

<LineGraph
  points={temps}
  animated={true}
  color="#4484B2"
/>
```

**Comment by abbottdev** [comment]
Also having this issue. I think it's been fixed by this PR: https://github.com/margelo/react-native-graph/pull/52/files but it's not had a new release yet. @chrispader @gtokman @mrousavy  could we get a new version published?

**Comment by chrispader** [comment]
this should be fixed with the latest update. If it's not, we can reopen this issue. I'll close it for now
