### ISSUE TITLE
Graph show empty

### ISSUE THREAD

**Issue by vtantai99** [margelo/react-native-graph#54]
<img width="344" alt="Screenshot 2022-12-04 at 16 34 54" src="https://user-images.githubusercontent.com/88877876/205483714-c187f2bf-498a-4d71-9c3b-879d3a5698d4.png">

**Comment by chezhe** [comment]
Same here, building with expo

**Comment by IgnacioMadariaga** [comment]
I have the same issue, my steps to reproduce these bug:

`Expo init <name-project>`
```
yarn add [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated)
```

after this, I added the react-native plugin into babel.confib.ts

```
yarn add [react-native-gesture-handler](https://github.com/software-mansion/react-native-gesture-handler)
yarn add [@shopify/react-native-skia](https://github.com/Shopify/react-native-skia)
yarn add react-native-graph
```

Later, in App.tsx, I added:

 <LineGraph points={array: GraphPoint[]} isAnimated={false} color: '#fff' />
 
 And these render a white panel

**Comment by chezhe** [comment]
This PR https://github.com/margelo/react-native-graph/pull/58 fixed this. I just remove the package and copy the files I need into my project, it works.

**Comment by IgnacioMadariaga** [comment]
@chezhe how u run the project? These solution didn't work for me

**Comment by chezhe** [comment]
> @chezhe how u run the project? These solution didn't work for me

I just copied the files I need into my project, and change the line of this PR https://github.com/margelo/react-native-graph/pull/58/files#diff-06fd647238a64a5d74ab05762e14c45040bde793aa467df2686d9e3d71d72162L224

For you, you can use `patch-package`,  after `yarn install`, change the file as above PR, and patch it.

Anyway, the package itself has bug, and that PR fixed it.

**Comment by edreyyo** [comment]
@chezhe @IgnacioMadariaga does `react-native-graph` work with Expo? I read it was unsupported because of Skia

**Comment by chezhe** [comment]
Expo supports Skia, you can find more info here https://docs.expo.dev/versions/latest/sdk/skia/

**Comment by IgnacioMadariaga** [comment]
@edreyyo I think should work, as @chezhe say before, I'm actually running a expo project using skia

**Comment by daginfinity** [comment]
Hi,
@chezhe I tried this solution by modifying the `CreateGraphPath.ts` file like below, I still have an empty graph.
Did I miss something ?
Maybe could you please provide an example array of 'points' ?

**My Component:**
```js
const priceHistory = generateRandomGraphData(70);
// console.log(priceHistory);
// const priceHistory = [];

class StockLineChartNew extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <LineGraph
          points={priceHistory}
          //   animated={true}
          color="#4484B2"
          //   enablePanGesture={true}
          //   onGestureStart={() => hapticFeedback('impactLight')}
          //   onPointSelected={(p) => updatePriceTitle(p)}
          //   onGestureEnd={() => resetPriceTitle()}
        />
      </View>
    );
  }
}
```

**The Node modules changes:**
```ts
// Calculates how many points between two points must be
    // calculated and drawn onto the canvas
    const drawingFactor = pixelFactorX(
      point.date,
      range.x.min,
      range.x.max
    )
```

**package.json**
```json

  "dependencies": {
    "@shopify/react-native-skia": "0.1.157",
    "expo": "~47.0.13",
    "patch-package": "^6.5.1",
    "react": "18.1.0",
    "react-native": "0.70.5",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-graph": "^0.3.0",
    "react-native-reanimated": "~2.12.0",
....
  },
```

**Comment by chezhe** [comment]
@daginfinity I didn't install this package, just copied those files I need. like this

![Screenshot 2023-02-08 at 08 39 11](https://user-images.githubusercontent.com/2902414/217399226-c10e043e-adb8-4b63-ba34-b1aea9b27598.png)

**Comment by daginfinity** [comment]
> @daginfinity I didn't install this package, just copied those files I need. like this
> 
> ![Screenshot 2023-02-08 at 08 39 11](https://user-images.githubusercontent.com/2902414/217399226-c10e043e-adb8-4b63-ba34-b1aea9b27598.png)

My project is in JS not TS. So it's complicated
