### ISSUE TITLE
Cant get the pan scrubbing to work even when setting animated to true and enablePanGesture to true

### ISSUE THREAD

**Issue by ChaseK30** [margelo/react-native-graph#59]
Cant get the pan scrubbing to work even when setting animated to true and enablePanGesture to true...When clicking and dragging on the app in ios sim nothing seems to be happening

**Comment by ChaseK30** [comment]
Cant get the pan to work on the example either

**Comment by Joelis57** [comment]
How did you solve this?

**Comment by brunohkbx** [comment]
For future reference: I ran into the same issue and I realized it's due to the `panGestureDelay` as called out in the README:
> panGestureDelay: Set delay for the pan gesture to activate. Set to 0 to start immediately after touch. Defaults to 300.
