### ISSUE TITLE
Animation does not work with large data set and crashes on navigation back

### ISSUE THREAD

**Issue by neo773** [margelo/react-native-graph#77]
Hi,

Been tinkering around with the library to integrate in my App, but couldn't get it to work with a dataset of 300 points.
The animation does not work when mutating the chartData and the App crashes when navigating back to previous screen.

I have made a minimal reproducible repo on GitHub https://github.com/neo773/react-native-graph-repro-bug 

https://github.com/margelo/react-native-graph/assets/62795688/c59b72b5-16e3-4c9f-9b4b-88ef97bf185c

**Comment by TFRadicalImaging** [comment]
I agree. The animation change is not working.
