### ISSUE TITLE
Version 1.0.2 is not working

### ISSUE THREAD

**Issue by XantreGodlike** [margelo/react-native-graph#78]
New version is not working.
I have an error. All is working fine on 1.0.1. 
React native reanimated 2.17.0
@shopify/react-native-skia: ^0.1.193

![Screenshot_2023-06-09-16-43-34-522_com](https://github.com/margelo/react-native-graph/assets/57757211/08621b2e-7f51-47c2-95e3-ff1ed2635735)

**Comment by XantreGodlike** [comment]
But all is working fine with `react-native-reanimated` 3.2.0

**Comment by ziziele** [comment]
I get the same error.

**Comment by XantreGodlike** [comment]
I've upgraded reanimated to version `3.2.0`

**Comment by Montchy** [comment]
It seems like the issue was resolved by using a newer version of reanimated :)
