### ISSUE TITLE
Q: How to render current point data correctly?

### ISSUE THREAD

**Issue by DDushkin** [margelo/react-native-graph#8]
Initially, the UI on gestures works pretty well.

![without setState](https://user-images.githubusercontent.com/25999628/167126603-cd65326a-2247-4872-99b5-e37eb531418d.gif)

But if I try to render the current point price and timestamp I get a laggy thing. Here is an example of code with `setState`:
```jsx
    const onPointSelected = useCallback(
        (p) => {
            console.log(p);

            const selectedPrice = formatAmount(p.value, fiatCurrency.code as CurrencyName, "fiat");
            const timestamp = DateTime.fromSeconds(p.date);

            setAmountTitle(selectedPrice);
            setTimestamp(timestamp);
        },
        [fiatCurrency.code],
    );
```
As a result with `setState` I get slow UI:

![with setState](https://user-images.githubusercontent.com/25999628/167126398-443ed007-5928-4578-98fc-c865d69337dd.gif)

So the question is how to render it properly and smoothly?

**Comment by mrousavy** [comment]
Yeah, that's because of React Native. It isn't really fast at state updates. Maybe this will improve with concurrent mode. The way to solve this is to use Reanimated Shared Values and update the Text using ReanimatedText.

**Comment by Angelk90** [comment]
@DDushkin : Have you tested the enablePanGesture on a physical device on android?
Not working.

**Comment by DDushkin** [comment]
> Yeah, that's because of React Native. It isn't really fast at state updates. Maybe this will improve with concurrent mode. The way to solve this is to use Reanimated Shared Values and update the Text using ReanimatedText.

Thanks, I installed `AnimateableText from "react-native-animateable-text"`, and here is the new code
```tsx
    const title = useSharedValue(assetBalanceFormatted);
    const subtitle = useSharedValue(`${t("main.value")}: ${fiatBalanceFormatted}`);

    const animatedTitle = useAnimatedProps(() => ({
        text: title.value,
    }));
    const animatedSubtitle = useAnimatedProps(() => ({
        text: subtitle.value,
    }));

    const onPointSelected = useCallback(
        (p) => {
            console.log(p);

            const selectedPrice = formatAmount(p.value, fiatCurrency.code as CurrencyName, "fiat");
            const timestamp = DateTime.fromSeconds(p.date);

            title.value = selectedPrice;
            subtitle.value = timestamp.toFormat("d MMM yyyy HH:mm");
        },
        [fiatCurrency.code, subtitle, title],
    );
//...
    <AnimateableText animatedProps={animatedTitle} style={styles.title} />
    <AnimateableText animatedProps={animatedSubtitle} style={styles.subtitle} />
```

But I can see now that `Cursor` is not rendered

![Запись экрана 2022-05-06 в 15 50 43](https://user-images.githubusercontent.com/25999628/167134797-e335f13c-c3d7-4b8f-9c71-d3ee73d40f66.gif)

**Comment by DDushkin** [comment]
> @DDushkin : Have you tested the enablePanGesture on a physical device on android? Not working.

Haven't tried on the device yet

**Comment by Angelk90** [comment]
@DDushkin : How did you manage to put that control line you see in the first picture?

**Comment by DDushkin** [comment]
> @DDushkin : How did you manage to put that control line you see in the first picture?

Added it manually in a fork

**Comment by DDushkin** [comment]
@mrousavy so in the end for me `Cursor` is not get rendered when I either do not have `onPointSelected` at all or when I change `setState` to `sharedValues`

**Comment by Angelk90** [comment]
> > @DDushkin : How did you manage to put that control line you see in the first picture?
> 
> Added it manually in a fork

It would be great if you could do a pr.

**Comment by sai-eashwar-groww** [comment]
I also needed to display a formatted timestamp without using `react-native-animateable-text`. I tried using reanimated's shared value, but ran into difficulties formatting the timestamp within the `worklet` function since I couldn't call `Date` object's methods or other libraries like `dayjs`. To work around this, I used react-native's TextInput and updated the text using `setNativeProps`, which seems to be working seamlessly.
So the corresponding props of LineGraph would be like this
```typescript
onGestureStart={() => {
	gestureStarted.current = true;
}}
onPointSelected={(point) => {
	if (!gestureStarted.current || point.value === null) {
		return;
	}
	const dayjsDate = dayjs(point.date);

	const time = dayjsDate.format('h:mm A');
	const date = dayjsDate.format('DD MMM');
	const year = dayjsDate.format('YYYY');

	let copySuffix: string;
	switch (graphSelected) {
		case '1D':
			copySuffix = time;
			break;
		case '1W':
		case '1M':
			copySuffix = `${time}, ${date}`;
			break;
		case '1Y':
		case '3Y':
		case '5Y':
			copySuffix = `${date} ${year}`;
	}

	selectedPriceRef.current?.setNativeProps({
		text: `${formatNumber(point.value, numberConfig.USD_DECIMAL)}${
			copySuffix ? ' | ' + copySuffix : ''
		}`,
	});
}}
onGestureEnd={() => {
	gestureStarted.current = false;
	selectedPriceRef.current?.setNativeProps({ text: '' });
}}
```

The refs are defined as 
```typescript
const selectedPriceRef = useRef<TextInput>(null);
const gestureStarted = useRef(false);
```

And the TextInput would be like this
```typescript
<TextInput
  underlineColorAndroid="transparent"
  editable={false}
  ref={selectedPriceRef}
/>
```

**Comment by SaiEashwarKS** [comment]
I also needed to display a formatted timestamp without using `react-native-animateable-text`. I tried using `reanimated's` shared value, but ran into difficulties formatting the timestamp within the `worklet` function since I couldn't call methods of `Date` or other libraries like `dayjs`. To work around this, I used react-native's `TextInput` and updated the text using `setNativeProps`, which seems to be working seamlessly.

So the corresponding props of `LineGraph` would be like this
```typescript
onGestureStart={() => {
	gestureStarted.current = true;
}}
onPointSelected={(point) => {
	if (!gestureStarted.current) {
		return;
	}

	selectedPriceRef.current?.setNativeProps({
		text: `${point.value}, ${dayjs(point.date).format('DD MMM')}`,
	});
}}
onGestureEnd={() => {
	gestureStarted.current = false;
	selectedPriceRef.current?.setNativeProps({ text: '' });
}}
```

The refs are defined as 
```typescript
const selectedPriceRef = useRef<TextInput>(null);
const gestureStarted = useRef(false);
```

And the TextInput would be like this
```jsx
<TextInput
  underlineColorAndroid="transparent"
  editable={false}
  ref={selectedPriceRef}
/>
```
