### ISSUE TITLE
How to make the line thinner please?

### ISSUE THREAD

**Issue by ziziele** [margelo/react-native-graph#82]
![Screenshot 2023-06-30 141808](https://github.com/margelo/react-native-graph/assets/73204106/d62d88dd-6703-408c-be27-083c9bcc7cfd)

**Comment by dowon938** [comment]
`<LineGraph
        points={graphData}
        color="#f1b13cff"
        lineThickness={2}
      />`
      like this

**Comment by ziziele** [comment]
So awesome! Thank you!
