### ISSUE TITLE
Feature policy and roadmap clarification request

### ISSUE THREAD

**Issue by vm-agnislav** [margelo/react-native-graph#91]
Hi everybody.

I'd like to understand the $subj better, because it's looks like quite... unclear and anarchy-driven here. 

First - thanks everyone involved for this awesome library. Thanks for your efforts - it's amazing. We use it and happy... yet. 

So, the feature we need is to show "outliers", like was described in #20 and I believe I saw similar in other issues. This feature was added in #55 on Jan 23rd of this year. And then it was removed in less than a month in #62 on Feb 20th. Both PRs were positioned as improvements, and I believe there were reasons for it, but from an external view it looks like continuous improvements on a pencil factory: 

> In a pencil factory, one engineer suggested not filling the last centimeter of pencils with lead to save on graphite, as this part was rarely used. Building on this, another engineer later proposed shortening the pencils by that centimeter to also save on wood, optimizing resource use without affecting usability.

For us this feature is quite crucial and we'd like to understand this package future and principles and priorities on feature delivery and accepting PRs.

Thanks.

**Comment by jtdaugh** [comment]
+1. Its a real bummer that theres no way to remove or control smoothing w/ this library.

**Comment by vm-agnislav** [comment]
So, we had to migrate to another library. Sad, I really liked this one. Closing as abandoned.
