### ISSUE TITLE
Chart doesn't reflect dataset

### ISSUE THREAD

**Issue by kokosky93** [margelo/react-native-graph#93]
Hi, I am trying to use react native graph however in my opinion something is wrong with this library.

Please take a look at the chart. It doesn't look like the dataset. Do you agree with me?

` const numberArray: Array<number> = [0, 20, 100, 0, 100, 100, 10, 0];
  const graphPoints: GraphPoint[] = numberArray.map((x, index) => {
    return {
      value: x,
      date: new Date( new Date(2000, 0, 1).getTime() + 1000 * 60 * 60 * 24 * index ),
    };
  });`

<img width="340" alt="Zrzut ekranu 2023-12-26 o 18 09 06" src="https://github.com/margelo/react-native-graph/assets/54596576/fd52fe21-84d8-49b7-aa35-3af8f2e958b2">

@mrousavy am i doing anything wrong?

**Comment by NationalDynamics** [comment]
> Hi, I am trying to use react native graph however in my opinion something is wrong with this library.
> 
> Please take a look at the chart. It doesn't look like the dataset. Do you agree with me?
> 
> ` const numberArray: Array<number> = [0, 20, 100, 0, 100, 100, 10, 0]; const graphPoints: GraphPoint[] = numberArray.map((x, index) => { return { value: x, date: new Date( new Date(2000, 0, 1).getTime() + 1000 * 60 * 60 * 24 * index ), }; });`
> 
> <img alt="Zrzut ekranu 2023-12-26 o 18 09 06" width="340" src="https://private-user-images.githubusercontent.com/54596576/292898975-fd52fe21-84d8-49b7-aa35-3af8f2e958b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NzQ1MzcsIm5iZiI6MTcwNDU3NDIzNywicGF0aCI6Ii81NDU5NjU3Ni8yOTI4OTg5NzUtZmQ1MmZlMjEtODRkOC00OWI3LWFhMzUtM2FmOGYyZTk1OGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDIwNTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ZjJhNDliYzYwYmFlMTM5NWNmZDg5MjlhZjA4Y2E0Yjk4ZTc3ZjEwMWFkNmZjMDYxMmQwMjY1ZjNlYmMwODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tmyRwFlT5TI7hUjFSCxd8Ruk9ocyU645BrJXfIVTZio">
> @mrousavy am i doing anything wrong?

Same here, the values are correct for me but the graph will show a line that is increasing even though the value shows dips....

**Comment by gonzalo-wallbit** [comment]
yeah, it's working bad. What a pity

**Comment by jasonleibowitz** [comment]
I ran into this issue as well. I think this issue arises when your dataset skips date ranges, or if the datetime is not in UTC. In my usage, I had a list of objects reflecting a `count` per day. However, for days without any values they were skipped, causing the chart to _not_ match the data. 

After ensuring that all days were present in the list, even with a `count` of 0, that resolved this issue. I also had to update all of the dates to be in UTC. 

Hopefully that helps others experiencing this?

**Comment by theblondealex** [comment]
This issue still occurs, Look at the test input data below

const defaultData: GraphPoint[] = [
  { date: new Date(2000, 0, 1), value: 0 },
  { date: new Date(2000, 0, 2), value: 1 },
  { date: new Date(2000, 0, 3), value: 0.4 },
  { date: new Date(2000, 0, 4), value: 0.2 },
  { date: new Date(2000, 0, 5), value: 0.8 },
  { date: new Date(2000, 0, 6), value: 0.6 },
  { date: new Date(2000, 0, 7), value: 0.4 },
  { date: new Date(2000, 0, 8), value: 0.7 },
  { date: new Date(2000, 0, 9), value: 0.5 },
  { date: new Date(2000, 0, 10), value: 1 },
  { date: new Date(2000, 0, 11), value: 0.9 },
  { date: new Date(2000, 0, 12), value: 0.6 },
];

results in this image

![image](https://github.com/margelo/react-native-graph/assets/65453441/9b42fd22-9242-45c3-8d32-eba04013400c)

where you can see the first peak is the value 1 and the last peak is also 1 (verified by consolelog) but they are not at the same height

the max point should be 1 whicH appears twice so there should be two peaks at the same height one at the start and one near the end but the one at the end is almost double the first one

**Comment by mrousavy** [comment]
Yea this is the chart smoothing I built. It sacrifices accuracy for better visuals, we can add a prop to disable that smoothing to present accurate data for such extreme values. If someone submits a PR for that prop I can gladly review & merge that :)

**Comment by theblondealex** [comment]
Ah gotcha, good to know the reason as my debugging was way off that being the reason 😆 I'll try look into disabling the smoothing if I can, thanks marc as always

**Comment by chrispader** [comment]
> Yea this is the chart smoothing I built. It sacrifices accuracy for better visuals, we can add a prop to disable that smoothing to present accurate data for such extreme values. If someone submits a PR for that prop I can gladly review & merge that :)

@mrousavy i'm gonna add this over the weekend.

**Comment by mrousavy** [comment]
muchos gracias senor

**Comment by chrispader** [comment]
We'll soon merge [a PR](https://github.com/margelo/react-native-graph/pull/100) that adds a `disableSmoothing` prop to `<LineGraph />`, which let's you disable the smoothing logic that @mrousavy mentioned.

This will remove any inaccuracies with the dataset. A new NPM version should be out soon!

Closing this issue for now. If something doesn't work, let me know.

**Comment by techlabz** [comment]
@chrispader the current PR still doesn't solve the issues 

Multiple data points on same day and also if there is a break with the dates on data does not show correctly

**Comment by christophby** [comment]
@chrispader any updates on this?
